# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Juan Agüí
description: > # this means to ignore newlines until "baseurl:"
  Juan Agüí is the co-founder of Tesla Cool Lab and loves writing about coding and education.
author: Juan Agüí
url: "https://juanagui.com" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog


email: juan@juanagui.com
google_analytics: UA-38637826-2
avatar: retrato-2021.png
email: juan@juanagui.com
github: jagui
linkedin: juanagui
disqus: juanagui.disqus.com

# Jekyll SEO
logo: /static/img/favicon.png
social:
  name: Juan Agüí
  links:
    - https://github.com/jagui
    - https://www.linkedin.com/in/juanagui

# Resume
name: Juan Agüí
email_full: mailto:juan@juanagui.com
website: juanagui.com
website_full: http://juanagui.com

# Build settings
markdown: kramdown
highlighter: rouge
rdiscount:
  extensions: [smart]
permalink: none
paginate: 5
safe: true
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jemoji
  - jekyll-sitemap
  - jekyll-seo-tag
exclude: ['Gemfile', 'Gem.lock','vendor','.venv','.vscode']
