# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Juan Agüí
author: Juan Agüí
email: juan@juanagui.com
description: > # this means to ignore newlines until "baseurl:"
  Juan Agüí is the co-founder of Tesla Cool Lab and loves writing about coding and education.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: juanagui
github_username:  jagui
google_analytics: UA-38637826-2
avatar: juanagui.jpg
email: juan@juanagui.com
github: jagui # username
twitter: juanagui
linkedin: juanagui

#Resume
name: Juan Agüí
email_full: mailto:juan@juanagui.com
website: juanagui.com
website_full: http://juanagui.com
tel: +34 669 528872
tel_full: tel:+34669528872
google_maps: 'https://goo.gl/maps/vh8cikt7sP82'
address: C/Monasterio de las Batuecas 15
postcode: 28049
city: Madrid
country: Spain

# Build settings
markdown: kramdown
highlighter: rouge
rdiscount:
  extensions: [smart]
permalink: none
paginate: 5
safe: true
gems:
  - jekyll-feed
  - jekyll-paginate
  - jemoji
exclude:
  - Gemfile
  - Gemfile.lock
